version: '3.9'

services:

  web:
    image: nameofmyuser/llm:web
    depends_on:
      - server
    ports:
      - 3000:3000
  
  server:
    image: nameofmyuser/llm:server
    ports:
      - 3001:3001
